/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;
import Model.*;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class frmMenu extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public frmMenu() {
        initComponents();
        setLocationRelativeTo(null);

        Login login = new Login();
        txtUsuario.setText(login.getUsuario());

        img.setText("");
        img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/usuario.png")));
        
       timer.start();
        timer2.start();
    }

    Integer tamPanel = 25;

    Timer timer = new Timer(50, new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            if (tamPanel > 155) {
                timer.stop();
            } else {
                tamPanel += 25;
                jPanel3.setSize(jPanel3.getWidth(), tamPanel);
            }
        }
    });

    Integer tamPanel2 = 30;
    Timer timer2 = new Timer(50, new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            if (tamPanel2 > 110) {
                timer2.stop();
            } else {
                tamPanel2 += 30;
                jPanel4.setSize(jPanel4.getWidth(), tamPanel2);
            }
        }
    });

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgS = new javax.swing.ButtonGroup();
        tbnS = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        img = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        tbtnGerenciar = new javax.swing.JToggleButton();
        tbtnPedidos = new javax.swing.JToggleButton();
        tbtnServicos = new javax.swing.JToggleButton();
        tbtnClientes = new javax.swing.JToggleButton();
        jPanel4 = new javax.swing.JPanel();
        btnConfiguracoes = new javax.swing.JToggleButton();
        btnSair = new javax.swing.JButton();
        tbtnConta = new javax.swing.JToggleButton();
        desktopPane = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 255));

        img.setText("Imagem");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(img)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(img)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtUsuario.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        txtUsuario.setForeground(new java.awt.Color(255, 255, 255));
        txtUsuario.setText("Usuário");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/logo.png"))); // NOI18N
        jLabel1.setText(" ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 833, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(14, 14, 14))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(txtUsuario)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(0, 102, 255));

        jPanel3.setBackground(new java.awt.Color(0, 153, 255));

        tbtnGerenciar.setBackground(new java.awt.Color(0, 153, 255));
        tbtnGerenciar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tbtnGerenciar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/setabaixo.png"))); // NOI18N
        tbtnGerenciar.setSelected(true);
        tbtnGerenciar.setText("Gerenciar");
        tbtnGerenciar.setBorderPainted(false);
        tbtnGerenciar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tbtnGerenciarFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tbtnGerenciarFocusLost(evt);
            }
        });
        tbtnGerenciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtnGerenciarActionPerformed(evt);
            }
        });

        tbtnPedidos.setBackground(new java.awt.Color(0, 153, 255));
        btgS.add(tbtnPedidos);
        tbtnPedidos.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        tbtnPedidos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/pedidos.png"))); // NOI18N
        tbtnPedidos.setText("Pedidos");
        tbtnPedidos.setBorder(null);
        tbtnPedidos.setOpaque(true);
        tbtnPedidos.setPreferredSize(new java.awt.Dimension(45, 16));
        tbtnPedidos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                tbtnPedidosItemStateChanged(evt);
            }
        });
        tbtnPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtnPedidosActionPerformed(evt);
            }
        });

        tbtnServicos.setBackground(new java.awt.Color(0, 153, 255));
        btgS.add(tbtnServicos);
        tbtnServicos.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        tbtnServicos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/servicos.png"))); // NOI18N
        tbtnServicos.setText("Serviços");
        tbtnServicos.setBorder(null);
        tbtnServicos.setPreferredSize(new java.awt.Dimension(45, 16));
        tbtnServicos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                tbtnServicosItemStateChanged(evt);
            }
        });
        tbtnServicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtnServicosActionPerformed(evt);
            }
        });

        tbtnClientes.setBackground(new java.awt.Color(0, 153, 255));
        btgS.add(tbtnClientes);
        tbtnClientes.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        tbtnClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/clientes.png"))); // NOI18N
        tbtnClientes.setText("Clientes");
        tbtnClientes.setBorder(null);
        tbtnClientes.setBorderPainted(false);
        tbtnClientes.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                tbtnClientesItemStateChanged(evt);
            }
        });
        tbtnClientes.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tbtnClientesFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tbtnClientesFocusLost(evt);
            }
        });
        tbtnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtnClientesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tbtnGerenciar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tbtnPedidos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tbtnServicos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tbtnClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(tbtnGerenciar)
                .addGap(1, 1, 1)
                .addComponent(tbtnClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tbtnPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tbtnServicos, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(0, 153, 255));

        btnConfiguracoes.setBackground(new java.awt.Color(0, 153, 255));
        btgS.add(btnConfiguracoes);
        btnConfiguracoes.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        btnConfiguracoes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/config.png"))); // NOI18N
        btnConfiguracoes.setText("Configurações");
        btnConfiguracoes.setBorder(null);
        btnConfiguracoes.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                btnConfiguracoesItemStateChanged(evt);
            }
        });
        btnConfiguracoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfiguracoesActionPerformed(evt);
            }
        });

        btnSair.setBackground(new java.awt.Color(0, 153, 255));
        btnSair.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/sair.png"))); // NOI18N
        btnSair.setText("Sair");
        btnSair.setBorder(null);
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        tbtnConta.setBackground(new java.awt.Color(0, 153, 255));
        tbtnConta.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tbtnConta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/setabaixo.png"))); // NOI18N
        tbtnConta.setSelected(true);
        tbtnConta.setText("Conta");
        tbtnConta.setBorder(null);
        tbtnConta.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tbtnContaFocusLost(evt);
            }
        });
        tbtnConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtnContaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tbtnConta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnConfiguracoes, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
            .addComponent(btnSair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(tbtnConta, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnConfiguracoes, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        desktopPane.setBackground(new java.awt.Color(0, 0, 102));
        desktopPane.setForeground(new java.awt.Color(255, 255, 255));
        desktopPane.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                desktopPaneComponentAdded(evt);
            }
            public void componentRemoved(java.awt.event.ContainerEvent evt) {
                desktopPaneComponentRemoved(evt);
            }
        });
        desktopPane.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                desktopPaneFocusGained(evt);
            }
        });
        desktopPane.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                desktopPaneComponentHidden(evt);
            }
        });

        javax.swing.GroupLayout desktopPaneLayout = new javax.swing.GroupLayout(desktopPane);
        desktopPane.setLayout(desktopPaneLayout);
        desktopPaneLayout.setHorizontalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1022, Short.MAX_VALUE)
        );
        desktopPaneLayout.setVerticalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 461, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(desktopPane))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(desktopPane)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbtnGerenciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtnGerenciarActionPerformed
        
        if (tbtnGerenciar.isSelected()) {
            timer.start();
        } else {
            timer.stop();
            tamPanel = 30;
            jPanel3.setSize(jPanel3.getWidth(), 30);
        }
        
    }//GEN-LAST:event_tbtnGerenciarActionPerformed

    private void tbtnPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtnPedidosActionPerformed
        desktopPane.removeAll();
        desktopPane.updateUI();
        
        if (tbtnPedidos.isSelected()) {

            desktopPane.removeAll();

            ifrmPedidos ifrm = new ifrmPedidos();

            Dimension desktopTamanho = desktopPane.getSize();
            Dimension ifrmTamanho = ifrm.getSize();

            int x = (desktopTamanho.width - ifrmTamanho.width) / 2;
            int y = (desktopTamanho.height - ifrmTamanho.height) / 2;

            ifrm.setLocation(x, y);

            desktopPane.add(ifrm);

            ifrm.setVisible(true);
        }
    }//GEN-LAST:event_tbtnPedidosActionPerformed

    private void tbtnServicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtnServicosActionPerformed
        desktopPane.removeAll();
        desktopPane.updateUI();

        if (tbtnServicos.isSelected()) {

            desktopPane.removeAll();

            ifrmServicos ifrm = new ifrmServicos();

            Dimension desktopTamanho = desktopPane.getSize();
            Dimension ifrmTamanho = ifrm.getSize();

            int x = (desktopTamanho.width - ifrmTamanho.width) / 2;
            int y = (desktopTamanho.height - ifrmTamanho.height) / 2;

            ifrm.setLocation(x, y);

            desktopPane.add(ifrm);

            ifrm.setVisible(true);
        }
    }//GEN-LAST:event_tbtnServicosActionPerformed

    private void tbtnContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtnContaActionPerformed
        
        if (tbtnConta.isSelected()) {
            timer2.start();
        } else {
            timer2.stop();
            tamPanel2 = 30;
            jPanel4.setSize(jPanel4.getWidth(), 30);
        }
        
    }//GEN-LAST:event_tbtnContaActionPerformed

    private void tbtnGerenciarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tbtnGerenciarFocusLost

    
    }//GEN-LAST:event_tbtnGerenciarFocusLost

    private void tbtnContaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tbtnContaFocusLost

        /*
        timer2.stop();
        tamPanel2 = 30;
        jPanel4.setSize(jPanel4.getWidth(), 30);
        */
    }//GEN-LAST:event_tbtnContaFocusLost

    private void tbtnGerenciarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tbtnGerenciarFocusGained
        
    }//GEN-LAST:event_tbtnGerenciarFocusGained

    private void btnConfiguracoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfiguracoesActionPerformed
        desktopPane.removeAll();
        desktopPane.updateUI();

        desktopPane.removeAll();

        ifrmConta ifrm = new ifrmConta();

        Dimension desktopTamanho = desktopPane.getSize();
        Dimension ifrmTamanho = ifrm.getSize();

        int x = (desktopTamanho.width - ifrmTamanho.width) / 2;
        int y = (desktopTamanho.height - ifrmTamanho.height) / 2;

        ifrm.setLocation(x, y);

        desktopPane.add(ifrm);

        ifrm.setVisible(true);
    }//GEN-LAST:event_btnConfiguracoesActionPerformed

    private void tbtnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtnClientesActionPerformed
        tbtnClientes.setBackground(new java.awt.Color(204,255,255)); 
        
        desktopPane.removeAll();
        desktopPane.updateUI();

        desktopPane.removeAll();

        ifrmClientes ifrm = new ifrmClientes();

        Dimension desktopTamanho = desktopPane.getSize();
        Dimension ifrmTamanho = ifrm.getSize();

        int x = (desktopTamanho.width - ifrmTamanho.width) / 2;
        int y = (desktopTamanho.height - ifrmTamanho.height) / 2;

        ifrm.setLocation(x, y);

        desktopPane.add(ifrm);

        ifrm.setVisible(true);
      
    }//GEN-LAST:event_tbtnClientesActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        Login login = new Login();
        
        int op = JOptionPane.showConfirmDialog(null, String.format("Deseja mesmo sair, %s?", login.getUsuario()), "Confirme", JOptionPane.YES_NO_OPTION);
        if(op == JOptionPane.YES_OPTION){
            this.dispose();
        }
    }//GEN-LAST:event_btnSairActionPerformed

    private void desktopPaneComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_desktopPaneComponentAdded

    }//GEN-LAST:event_desktopPaneComponentAdded

    private void desktopPaneComponentRemoved(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_desktopPaneComponentRemoved
        tbnS.clearSelection();
        
        Login login = new Login();
        
        if(!login.isLoginValidado()){
            this.setVisible(false);
            this.dispose();
        }
    }//GEN-LAST:event_desktopPaneComponentRemoved

    private void desktopPaneComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_desktopPaneComponentHidden
        
    }//GEN-LAST:event_desktopPaneComponentHidden

    private void tbtnClientesFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tbtnClientesFocusGained
        // claro
    }//GEN-LAST:event_tbtnClientesFocusGained

    private void tbtnClientesFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tbtnClientesFocusLost
        
    }//GEN-LAST:event_tbtnClientesFocusLost

    private void tbtnClientesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_tbtnClientesItemStateChanged
        if(tbtnClientes.isSelected()){
            tbtnClientes.setBackground(new java.awt.Color(204,255,255)); 
        }
        if(!tbtnClientes.isSelected()){
            tbtnClientes.setBackground(new java.awt.Color(0,153,255));
        }
    }//GEN-LAST:event_tbtnClientesItemStateChanged

    private void tbtnPedidosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_tbtnPedidosItemStateChanged
        if(tbtnPedidos.isSelected()){
            tbtnPedidos.setBackground(new java.awt.Color(204,255,255)); 
        }
        if(!tbtnPedidos.isSelected()){
            tbtnPedidos.setBackground(new java.awt.Color(0,153,255));
        }
    }//GEN-LAST:event_tbtnPedidosItemStateChanged

    private void tbtnServicosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_tbtnServicosItemStateChanged
        if(tbtnServicos.isSelected()){
            tbtnServicos.setBackground(new java.awt.Color(204,255,255)); 
        }
        if(!tbtnServicos.isSelected()){
            tbtnServicos.setBackground(new java.awt.Color(0,153,255));
        }
    }//GEN-LAST:event_tbtnServicosItemStateChanged

    private void btnConfiguracoesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_btnConfiguracoesItemStateChanged
        if(btnConfiguracoes.isSelected()){
            btnConfiguracoes.setBackground(new java.awt.Color(204,255,255)); 
        }
        if(!btnConfiguracoes.isSelected()){
            btnConfiguracoes.setBackground(new java.awt.Color(0,153,255));
        }
    }//GEN-LAST:event_btnConfiguracoesItemStateChanged

    private void desktopPaneFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_desktopPaneFocusGained
        btgS.clearSelection();
    }//GEN-LAST:event_desktopPaneFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btgS;
    private javax.swing.JToggleButton btnConfiguracoes;
    private javax.swing.JButton btnSair;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JLabel img;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.ButtonGroup tbnS;
    private javax.swing.JToggleButton tbtnClientes;
    private javax.swing.JToggleButton tbtnConta;
    private javax.swing.JToggleButton tbtnGerenciar;
    private javax.swing.JToggleButton tbtnPedidos;
    private javax.swing.JToggleButton tbtnServicos;
    private javax.swing.JLabel txtUsuario;
    // End of variables declaration//GEN-END:variables
}
