/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package View;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import Model.*;
import Controller.*;

/**
 *
 * @author LABINFO
 */
public class ifrmConta extends javax.swing.JInternalFrame {

    /**
     * Creates new form ifrmConta
     */
    public ifrmConta() {
        initComponents();

        pssConfirmarSenha.setVisible(false);
        tgBtnConfirmarSenha.setVisible(false);
        jLabel7.setVisible(false);

        listar();
    }

    public void listar() {
        Login login = new Login();
        ConLogin conLogin = new ConLogin();

        txtUsuario.setText(login.getUsuario());
        login = conLogin.listar();
        pssSenha.setText(login.getSenha());

        Funcionarios funcionario = new Funcionarios();
        ConFuncionarios conFunc = new ConFuncionarios();

        funcionario = conFunc.listar(funcionario);
        txtCod.setText(String.valueOf(funcionario.getCodigo()));
        txtNome.setText(funcionario.getNome());
        txtTelefone.setText(funcionario.getTelefone());
        txtCpf.setText(funcionario.getCpf());
        txtEmail.setText(funcionario.getEmail());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        pssSenha = new javax.swing.JPasswordField();
        txtObrNome = new javax.swing.JLabel();
        txtObrTel = new javax.swing.JLabel();
        txtObrUsuario = new javax.swing.JLabel();
        txtObrCpf = new javax.swing.JLabel();
        txtObrSenha = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtTelefone = new javax.swing.JTextField();
        txtCpf = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        tgBtnSenha = new javax.swing.JToggleButton();
        jLabel7 = new javax.swing.JLabel();
        pssConfirmarSenha = new javax.swing.JPasswordField();
        tgBtnConfirmarSenha = new javax.swing.JToggleButton();
        txtObrConfirmarSenha = new javax.swing.JLabel();
        tbtnEditar = new javax.swing.JToggleButton();
        txtCod = new javax.swing.JTextField();
        tbtnNovaSenha = new javax.swing.JToggleButton();
        jButton1 = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel1.setText("Nome:");

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel2.setText("Telefone:");

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel3.setText("CPF:");

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel4.setText("Email:");

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel5.setText("Usuário:");

        txtUsuario.setBackground(new java.awt.Color(204, 204, 255));
        txtUsuario.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        txtUsuario.setEnabled(false);
        txtUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUsuarioFocusLost(evt);
            }
        });
        txtUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtUsuarioKeyPressed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel6.setText("Senha:");

        pssSenha.setBackground(new java.awt.Color(204, 204, 255));
        pssSenha.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        pssSenha.setEnabled(false);
        pssSenha.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                pssSenhaFocusLost(evt);
            }
        });
        pssSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pssSenhaActionPerformed(evt);
            }
        });
        pssSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pssSenhaKeyPressed(evt);
            }
        });

        txtObrNome.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        txtObrNome.setForeground(new java.awt.Color(255, 0, 51));

        txtObrTel.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        txtObrTel.setForeground(new java.awt.Color(255, 0, 51));

        txtObrUsuario.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        txtObrUsuario.setForeground(new java.awt.Color(255, 0, 51));

        txtObrCpf.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        txtObrCpf.setForeground(new java.awt.Color(255, 0, 51));

        txtObrSenha.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        txtObrSenha.setForeground(new java.awt.Color(255, 0, 51));

        txtNome.setBackground(new java.awt.Color(204, 204, 255));
        txtNome.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        txtNome.setEnabled(false);
        txtNome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNomeFocusLost(evt);
            }
        });
        txtNome.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txtNomeInputMethodTextChanged(evt);
            }
        });
        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });
        txtNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNomeKeyPressed(evt);
            }
        });

        txtTelefone.setBackground(new java.awt.Color(204, 204, 255));
        txtTelefone.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        txtTelefone.setEnabled(false);
        txtTelefone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTelefoneFocusLost(evt);
            }
        });
        txtTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefoneActionPerformed(evt);
            }
        });
        txtTelefone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTelefoneKeyPressed(evt);
            }
        });

        txtCpf.setBackground(new java.awt.Color(204, 204, 255));
        txtCpf.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        txtCpf.setEnabled(false);
        txtCpf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCpfFocusLost(evt);
            }
        });
        txtCpf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCpfKeyPressed(evt);
            }
        });

        txtEmail.setBackground(new java.awt.Color(204, 204, 255));
        txtEmail.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        txtEmail.setEnabled(false);
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        txtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtEmailKeyPressed(evt);
            }
        });

        tgBtnSenha.setBackground(new java.awt.Color(204, 255, 255));
        tgBtnSenha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/senhaVisivel.png"))); // NOI18N
        tgBtnSenha.setEnabled(false);
        tgBtnSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tgBtnSenhaActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel7.setText("Nova Senha:");

        pssConfirmarSenha.setBackground(new java.awt.Color(204, 204, 255));
        pssConfirmarSenha.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        pssConfirmarSenha.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                pssConfirmarSenhaFocusLost(evt);
            }
        });
        pssConfirmarSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pssConfirmarSenhaActionPerformed(evt);
            }
        });
        pssConfirmarSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pssConfirmarSenhaKeyPressed(evt);
            }
        });

        tgBtnConfirmarSenha.setBackground(new java.awt.Color(204, 255, 255));
        tgBtnConfirmarSenha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/senhaVisivel.png"))); // NOI18N
        tgBtnConfirmarSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tgBtnConfirmarSenhaActionPerformed(evt);
            }
        });

        txtObrConfirmarSenha.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        txtObrConfirmarSenha.setForeground(new java.awt.Color(255, 0, 51));

        tbtnEditar.setBackground(new java.awt.Color(204, 255, 255));
        tbtnEditar.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        tbtnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/editar.png"))); // NOI18N
        tbtnEditar.setText("Editar");
        tbtnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtnEditarActionPerformed(evt);
            }
        });

        txtCod.setBackground(new java.awt.Color(204, 204, 255));
        txtCod.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        txtCod.setEnabled(false);

        tbtnNovaSenha.setBackground(new java.awt.Color(204, 255, 255));
        tbtnNovaSenha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/editar2.png"))); // NOI18N
        tbtnNovaSenha.setEnabled(false);
        tbtnNovaSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtnNovaSenhaActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(204, 255, 255));
        jButton1.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jButton1.setText("X");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnExcluir.setBackground(new java.awt.Color(255, 0, 51));
        btnExcluir.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/apagar.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel8.setText("Código:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel5)
                                .addComponent(jLabel6)
                                .addComponent(jLabel7)
                                .addComponent(jLabel1)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2)
                                .addComponent(jLabel4))
                            .addComponent(jButton1)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCod, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(pssSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tgBtnSenha)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tbtnNovaSenha))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(pssConfirmarSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tgBtnConfirmarSenha)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtObrConfirmarSenha))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNome)
                                    .addComponent(txtTelefone)
                                    .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtObrTel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtObrNome))
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtObrUsuario)
                            .addComponent(txtObrSenha)
                            .addComponent(txtObrCpf)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(tbtnEditar)
                        .addGap(18, 18, 18)
                        .addComponent(btnExcluir)))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(txtObrCpf)
                        .addGap(94, 94, 94)
                        .addComponent(txtObrUsuario)
                        .addGap(18, 18, 18)
                        .addComponent(txtObrSenha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtObrNome))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)
                                    .addComponent(txtObrTel))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)))
                            .addComponent(jLabel1))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(pssSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6)))
                            .addComponent(tgBtnSenha)
                            .addComponent(tbtnNovaSenha))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(pssConfirmarSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7))
                            .addComponent(tgBtnConfirmarSenha)
                            .addComponent(txtObrConfirmarSenha))
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbtnEditar)
                    .addComponent(btnExcluir))
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsuarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUsuarioFocusLost
        if (txtUsuario.getText().trim().isEmpty()) {
            txtObrUsuario.setText("* Obrigatório");
        } else {
            txtObrUsuario.setText("");
        }
    }//GEN-LAST:event_txtUsuarioFocusLost

    private void txtUsuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsuarioKeyPressed
        if (txtUsuario.getText().trim().isEmpty()) {
            txtObrUsuario.setText("* Obrigatório");
        } else {
            if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
                pssSenha.requestFocus();
            }
        }
    }//GEN-LAST:event_txtUsuarioKeyPressed

    private void pssSenhaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pssSenhaFocusLost
        if (String.valueOf(pssSenha.getPassword()).trim().isEmpty()) {
            txtObrSenha.setText("* Obrigatório");
        } else {
            txtObrSenha.setText("");
        }
    }//GEN-LAST:event_pssSenhaFocusLost

    private void pssSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pssSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pssSenhaActionPerformed

    private void pssSenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pssSenhaKeyPressed
        if (String.valueOf(pssSenha.getPassword()).trim().isEmpty()) {
            txtObrSenha.setText("* Obrigatório");
        } else {
            if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
                txtObrSenha.setText("");
                pssConfirmarSenha.requestFocus();
            }
        }
    }//GEN-LAST:event_pssSenhaKeyPressed

    private void txtNomeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNomeFocusLost
        if (txtNome.getText().trim().isEmpty()) {
            txtObrNome.setText("* Obrigatório");
        } else {
            txtObrNome.setText("");
        }
    }//GEN-LAST:event_txtNomeFocusLost

    private void txtNomeInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txtNomeInputMethodTextChanged

    }//GEN-LAST:event_txtNomeInputMethodTextChanged

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed

    }//GEN-LAST:event_txtNomeActionPerformed

    private void txtNomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeKeyPressed
        if (txtNome.getText().trim().isEmpty()) {
            txtObrNome.setText("* Obrigatório");
        } else {
            if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
                txtObrNome.setText("");
                txtTelefone.requestFocus();
            }
        }
    }//GEN-LAST:event_txtNomeKeyPressed

    private void txtTelefoneFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTelefoneFocusLost
        if (txtTelefone.getText().trim().isEmpty()) {
            txtObrTel.setText("* Obrigatório");
        } else {
            txtObrTel.setText("");
            txtTelefone.setText(Formatacoes.formatarTelefone(txtTelefone.getText().trim()));
        }
    }//GEN-LAST:event_txtTelefoneFocusLost

    private void txtTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefoneActionPerformed

    private void txtTelefoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefoneKeyPressed
        if (txtTelefone.getText().trim().isEmpty()) {
            txtObrTel.setText("* Obrigatório");
        } else {
            if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
                txtCpf.requestFocus();
            }
        }
    }//GEN-LAST:event_txtTelefoneKeyPressed

    private void txtCpfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCpfFocusLost
        if (txtCpf.getText().trim().isEmpty()) {
            txtObrCpf.setText("* Obrigatório");
        } else {
            txtObrCpf.setText("");
            txtEmail.requestFocus();
        }
    }//GEN-LAST:event_txtCpfFocusLost

    private void txtCpfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCpfKeyPressed
        if (txtCpf.getText().trim().isEmpty()) {
            txtObrCpf.setText("* Obrigatório");
        } else {
            if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
                txtEmail.requestFocus();
            }
        }
    }//GEN-LAST:event_txtCpfKeyPressed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed

    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtEmailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtUsuario.requestFocus();
        }
    }//GEN-LAST:event_txtEmailKeyPressed

    private void tgBtnSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tgBtnSenhaActionPerformed
        if (tgBtnSenha.isSelected()) {
            pssSenha.setEchoChar((char) 0);
            tgBtnSenha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/senhaInvisivel.png")));
        } else {
            pssSenha.setEchoChar('*');
            tgBtnSenha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/senhaVisivel.png")));
        }
    }//GEN-LAST:event_tgBtnSenhaActionPerformed

    private void pssConfirmarSenhaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pssConfirmarSenhaFocusLost
        if (String.valueOf(pssConfirmarSenha.getPassword()).trim().isEmpty()) {
            txtObrConfirmarSenha.setText("* Obrigatório");
        } else {
            txtObrConfirmarSenha.setText("");
        }
    }//GEN-LAST:event_pssConfirmarSenhaFocusLost

    private void pssConfirmarSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pssConfirmarSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pssConfirmarSenhaActionPerformed

    private void pssConfirmarSenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pssConfirmarSenhaKeyPressed
        if (String.valueOf(pssConfirmarSenha.getPassword()).trim().isEmpty()) {
            txtObrConfirmarSenha.setText("* Obrigatório");
        } else {
            if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
                txtObrConfirmarSenha.setText("");
                // btnCadastrar.doClick();
            }
        }
    }//GEN-LAST:event_pssConfirmarSenhaKeyPressed

    private void tgBtnConfirmarSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tgBtnConfirmarSenhaActionPerformed
        if (tgBtnConfirmarSenha.isSelected()) {
            pssConfirmarSenha.setEchoChar((char) 0);
            tgBtnConfirmarSenha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/senhaInvisivel.png")));
        } else {
            pssConfirmarSenha.setEchoChar('*');
            tgBtnConfirmarSenha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/senhaVisivel.png")));
        }
    }//GEN-LAST:event_tgBtnConfirmarSenhaActionPerformed

    private void tbtnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtnEditarActionPerformed
        if (tbtnEditar.isSelected()) {
            txtNome.setEnabled(true);
            txtTelefone.setEnabled(true);
            txtEmail.setEnabled(true);
            
            tgBtnSenha.setEnabled(true);
            tbtnNovaSenha.setEnabled(true);
        }
        if (!tbtnEditar.isSelected()) {
            try {
                Login login = new Login();
                ConLogin conLogin = new ConLogin();

                Funcionarios funcionario = new Funcionarios();
                ConFuncionarios conFunc = new ConFuncionarios();

                if (txtTelefone.getText().trim().isEmpty() || txtNome.getText().trim().isEmpty()) {
                    JOptionPane.showMessageDialog(null, "Preencha os campos obrigatórios!", "Aviso", JOptionPane.WARNING_MESSAGE);
                } else {
                    int op = JOptionPane.showConfirmDialog(null, String.format("Deseja mesmo editar %s?", txtNome.getText().trim()), "Confirme", JOptionPane.YES_NO_OPTION);
                    if (op == JOptionPane.YES_OPTION) {
                        funcionario.setCodigo(Integer.parseInt(txtCod.getText()));
                        funcionario.setNome(txtNome.getText());
                        funcionario.setTelefone(txtTelefone.getText());
                        funcionario.setCpf(txtCpf.getText());
                        funcionario.setEmail(txtEmail.getText());
                        conFunc.editar(funcionario);
                        
                        if(tbtnNovaSenha.isSelected() && !String.valueOf(pssConfirmarSenha.getPassword()).trim().isEmpty()){
                            login.setUsuario(txtUsuario.getText());
                            login.setSenha(String.valueOf(pssConfirmarSenha.getPassword()).trim());
                            
                            conLogin.editar(login);
                        }

                        JOptionPane.showMessageDialog(null, "Perfil atualizado com sucesso!");

                        txtNome.setEnabled(false);
                        txtTelefone.setEnabled(false);
                        txtCpf.setEnabled(false);
                        txtEmail.setEnabled(false);
                        txtUsuario.setEnabled(false);
                        pssSenha.setEnabled(false);
                        tgBtnSenha.setEnabled(false);
                        tbtnNovaSenha.setEnabled(false);

                        pssConfirmarSenha.setVisible(false);
                        tgBtnConfirmarSenha.setVisible(false);
                        jLabel7.setVisible(false);

                        listar();
                        // limpar();
                    } else {
                        txtNome.setEnabled(false);
                        txtTelefone.setEnabled(false);
                        txtCpf.setEnabled(false);
                        txtEmail.setEnabled(false);
                        txtUsuario.setEnabled(false);
                        pssSenha.setEnabled(false);
                        tgBtnSenha.setEnabled(false);
                        tbtnNovaSenha.setEnabled(false);

                        pssConfirmarSenha.setVisible(false);
                        tgBtnConfirmarSenha.setVisible(false);
                        jLabel7.setVisible(false);
                        listar();
                    }
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }

        }
    }//GEN-LAST:event_tbtnEditarActionPerformed

    private void tbtnNovaSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtnNovaSenhaActionPerformed
        if (tbtnNovaSenha.isSelected()) {
            pssConfirmarSenha.setVisible(true);
            tgBtnConfirmarSenha.setVisible(true);
            jLabel7.setVisible(true);
        }
        if (!tbtnNovaSenha.isSelected()) {
            pssConfirmarSenha.setVisible(false);
            tgBtnConfirmarSenha.setVisible(false);
            jLabel7.setVisible(false);
        }
    }//GEN-LAST:event_tbtnNovaSenhaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        try {

            int op = JOptionPane.showConfirmDialog(null, String.format("Deseja mesmo excluir excluir sua conta, %s?", txtNome.getText().trim()), "Confirme", JOptionPane.YES_NO_OPTION);
            if (op == JOptionPane.YES_OPTION) {
                ConFuncionarios conFunc = new ConFuncionarios();

                int codigo = Integer.parseInt(txtCod.getText());

                conFunc.excluir(codigo);

                JOptionPane.showMessageDialog(null, "Conta excluida.", "Aviso", JOptionPane.WARNING_MESSAGE);
                
                Login login = new Login();
                login.setLoginValidado(false);

                this.setVisible(false);
                this.dispose();

                
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnExcluirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField pssConfirmarSenha;
    private javax.swing.JPasswordField pssSenha;
    private javax.swing.JToggleButton tbtnEditar;
    private javax.swing.JToggleButton tbtnNovaSenha;
    private javax.swing.JToggleButton tgBtnConfirmarSenha;
    private javax.swing.JToggleButton tgBtnSenha;
    private javax.swing.JTextField txtCod;
    private javax.swing.JTextField txtCpf;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNome;
    private javax.swing.JLabel txtObrConfirmarSenha;
    private javax.swing.JLabel txtObrCpf;
    private javax.swing.JLabel txtObrNome;
    private javax.swing.JLabel txtObrSenha;
    private javax.swing.JLabel txtObrTel;
    private javax.swing.JLabel txtObrUsuario;
    private javax.swing.JTextField txtTelefone;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
