/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package View;

import Controller.*;
import Model.*;
import java.text.NumberFormat;
import java.time.LocalDate;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.util.Locale;

/**
 *
 * @author User
 */
public class ifrmPedidos extends javax.swing.JInternalFrame {

    /**
     * Creates new form ifrmPedidos
     */
    public ifrmPedidos() {
        initComponents();

        System.out.println("");

        listar();
        ConServicos conServico = new ConServicos();

        cbTipos.setModel(new javax.swing.DefaultComboBoxModel<>(conServico.pegarTodosTipos()));

        cbTipos.setSelectedIndex(-1);

        spiQtd.setValue(1);
    }

    public void listar() {

        Vector cabecalho = new Vector();
        try {
            cabecalho.addElement("Serviço");
            cabecalho.addElement("Quantidade");
            cabecalho.addElement("Valor");

            cabecalho.addElement("Código");
            cabecalho.addElement("Cliente");
            cabecalho.addElement("Data");
            cabecalho.addElement("Status");

            ConPedidos conPedidos = new ConPedidos();
            ConAtendimentos conAtend = new ConAtendimentos();

            tbPedido.setModel(new DefaultTableModel(conAtend.listar(), cabecalho) {

                @Override
                public boolean isCellEditable(int row, int column) {
                    return false;
                }
            });

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro: " + e);
        }
    }

    public void pegarPedido(int codigo) {
        try {

            Pedidos pedido = new Pedidos();
            ConPedidos conpedido = new ConPedidos();

            Atendimentos atendimento = new Atendimentos();
            ConAtendimentos conAtend = new ConAtendimentos();

            ConFuncionarios conFunc = new ConFuncionarios();
            Funcionarios func = new Funcionarios();

            pedido = conpedido.pegarPedido(codigo);
            atendimento = conAtend.pegarAtendimento(codigo);

            txtCod.setText(String.valueOf(pedido.getCodigo()));
            txtCli.setText(String.valueOf(pedido.getCliente()));
            txtHora.setText(pedido.getHora());
            txtData.setText(pedido.getData());
            txtNomeCli.setText(pedido.getNomeCiente());

            String status = pedido.getStatus();

            switch (status) {
                case "Em preparação":
                    cbStatus.setSelectedIndex(0);
                    break;
                case "Aguardando Coleta":
                    cbStatus.setSelectedIndex(1);
                    break;
                case "Finalizado":
                    cbStatus.setSelectedIndex(2);
                    break;
            }

            cbTipos.setSelectedIndex(atendimento.getServico() - 1);
            spiQtd.setValue(atendimento.getQtd());
            txtPreco.setText(Formatacoes.formatarMoeda(atendimento.getPreco()));
            txtObs.setText(atendimento.getObs());

            func = conFunc.pegarFuncionario(func);

            txtFunc.setText(func.getNome());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    public void limpar() {
        txtCod.setText("");
        txtCli.setText("");
        txtHora.setText("");
        txtData.setText("");
        cbStatus.setSelectedIndex(-1);
        txtObs.setText("");
        cbTipos.setSelectedIndex(-1);
        spiQtd.setValue(0);
        txtPreco.setText("");
        txtNomeCli.setText("");
        txtFunc.setText("");

        clienteLink.setCodigoCliente(0);
        clienteLink.setNomeCliente("");

        txtObrTipo.setText("* Obrigatório");
        txtObrCliente.setText("* Obrigatório");
        txtObrStatus.setText("* Obrigatório");

        // validar
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtCod = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtHora = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtData = new javax.swing.JTextField();
        txtCli = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnSalvar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbPedido = new javax.swing.JTable();
        spiQtd = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtObs = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txtPreco = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        cbTipos = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        cbStatus = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        txtNomeCli = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        txtFunc = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtObrCliente = new javax.swing.JLabel();
        txtObrTipo = new javax.swing.JLabel();
        txtObrStatus = new javax.swing.JLabel();

        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));
        jPanel1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPanel1FocusGained(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel7.setText("Código:");

        txtCod.setBackground(new java.awt.Color(204, 204, 255));
        txtCod.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        txtCod.setEnabled(false);
        txtCod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel2.setText("Hora:");

        txtHora.setBackground(new java.awt.Color(204, 204, 255));
        txtHora.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel4.setText("Data:");

        txtData.setBackground(new java.awt.Color(204, 204, 255));
        txtData.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        txtData.setNextFocusableComponent(txtObs);

        txtCli.setBackground(new java.awt.Color(204, 204, 255));
        txtCli.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        txtCli.setEnabled(false);

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel5.setText("Cliente:");

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel6.setText("Status:");

        btnSalvar.setBackground(new java.awt.Color(204, 255, 255));
        btnSalvar.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/adicionar.png"))); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnLimpar.setBackground(new java.awt.Color(204, 255, 255));
        btnLimpar.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        btnLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/limpar.png"))); // NOI18N
        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        btnEditar.setBackground(new java.awt.Color(204, 255, 255));
        btnEditar.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/editar.png"))); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnCancelar.setBackground(new java.awt.Color(255, 0, 51));
        btnCancelar.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/apagar.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        tbPedido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbPedido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbPedidoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbPedido);

        spiQtd.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        spiQtd.setFocusable(false);
        spiQtd.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spiQtdStateChanged(evt);
            }
        });
        spiQtd.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                spiQtdFocusGained(evt);
            }
        });
        spiQtd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                spiQtdMouseClicked(evt);
            }
        });

        txtObs.setBackground(new java.awt.Color(204, 204, 255));
        txtObs.setColumns(20);
        txtObs.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        txtObs.setRows(5);
        jScrollPane1.setViewportView(txtObs);

        jButton1.setBackground(new java.awt.Color(204, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/relogio.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(204, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/calendario.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        txtPreco.setBackground(new java.awt.Color(204, 204, 255));
        txtPreco.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        txtPreco.setEnabled(false);

        jLabel8.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel8.setText("Tipo:");

        jLabel10.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel10.setText("Preço:");

        jLabel13.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel13.setText("Quantidade:");

        cbTipos.setBackground(new java.awt.Color(204, 204, 255));
        cbTipos.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        cbTipos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbTipos.setSelectedIndex(-1);
        cbTipos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbTiposItemStateChanged(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel3.setText("OBS:");

        cbStatus.setBackground(new java.awt.Color(204, 204, 255));
        cbStatus.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        cbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Em Preparação", "Aguardando Coleta", "Finalizado" }));
        cbStatus.setSelectedIndex(-1);
        cbStatus.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbStatusItemStateChanged(evt);
            }
        });
        cbStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbStatusActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(204, 255, 255));
        jButton3.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jButton3.setText("...");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        txtNomeCli.setBackground(new java.awt.Color(204, 204, 255));
        txtNomeCli.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        txtNomeCli.setEnabled(false);

        jButton4.setBackground(new java.awt.Color(204, 255, 255));
        jButton4.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jButton4.setText("X");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        txtFunc.setBackground(new java.awt.Color(204, 204, 255));
        txtFunc.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        txtFunc.setEnabled(false);

        jLabel9.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel9.setText("Funcionário:");

        txtObrCliente.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        txtObrCliente.setForeground(new java.awt.Color(255, 0, 51));
        txtObrCliente.setText("* Obrigatório");

        txtObrTipo.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        txtObrTipo.setForeground(new java.awt.Color(255, 0, 51));
        txtObrTipo.setText("* Obrigatório");

        txtObrStatus.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        txtObrStatus.setForeground(new java.awt.Color(255, 0, 51));
        txtObrStatus.setText("* Obrigatório");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancelar)
                        .addGap(86, 86, 86))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 757, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 54, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCli, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)
                                .addComponent(txtNomeCli, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtObrCliente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtObrStatus))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(46, 46, 46)
                                        .addComponent(jLabel8))
                                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(cbTipos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtObrTipo))
                                            .addComponent(spiQtd, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(txtCod, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel9)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtHora, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton2))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(51, 51, 51))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(cbTipos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtObrTipo))
                        .addGap(0, 135, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 103, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(spiQtd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10)
                                    .addComponent(cbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel5)
                                            .addComponent(txtCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtNomeCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButton3)
                                            .addComponent(txtObrCliente)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(txtObrStatus))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel2))
                                    .addComponent(jButton1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel4))
                                    .addComponent(jButton2))
                                .addGap(18, 18, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))))))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLimpar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnSalvar)
                        .addComponent(btnEditar)
                        .addComponent(btnCancelar)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained

    }//GEN-LAST:event_formFocusGained

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_formInternalFrameOpened

    private void jPanel1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPanel1FocusGained

    }//GEN-LAST:event_jPanel1FocusGained

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        frmMenu menu = new frmMenu();

        dialogClientes popup = new dialogClientes(menu, true);

        popup.setVisible(true);

        txtCli.setText(String.valueOf(clienteLink.getCodigoCliente()));
        txtNomeCli.setText(clienteLink.getNomeCliente());
        
        if(!txtNomeCli.getText().isEmpty()){
            txtObrCliente.setText("");
        }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void cbTiposItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbTiposItemStateChanged
        if (Integer.parseInt(spiQtd.getValue().toString()) > 0) {
            Servicos servico = new Servicos();
            ConServicos conservico = new ConServicos();

            servico = conservico.pesquisarTipoServ(cbTipos.getSelectedIndex() + 1);

            float preco = servico.getValor() * Integer.parseInt(String.valueOf(spiQtd.getValue()));

            txtPreco.setText(Formatacoes.formatarMoeda(preco));
        }

        if (cbTipos.getSelectedIndex() != -1) {
            txtObrTipo.setText("");
        }
    }//GEN-LAST:event_cbTiposItemStateChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        txtData.setText(String.valueOf(LocalDate.now()));
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        LocalTime hora = LocalTime.now();

        DateTimeFormatter formatador = DateTimeFormatter.ofPattern("HH:mm:ss");

        txtHora.setText(hora.format(formatador));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void spiQtdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_spiQtdMouseClicked

    }//GEN-LAST:event_spiQtdMouseClicked

    private void spiQtdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_spiQtdFocusGained

    }//GEN-LAST:event_spiQtdFocusGained

    private void spiQtdStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spiQtdStateChanged
        if (cbTipos.getSelectedIndex() != -1) {
            Servicos servico = new Servicos();
            ConServicos conservico = new ConServicos();

            servico = conservico.pesquisarTipoServ(cbTipos.getSelectedIndex() + 1);

            float preco = servico.getValor() * Integer.parseInt(String.valueOf(spiQtd.getValue()));

            txtPreco.setText(Formatacoes.formatarMoeda(preco));
        }

        if (Integer.parseInt(String.valueOf(spiQtd.getValue())) < 1) {
            spiQtd.setValue(1);
        }
    }//GEN-LAST:event_spiQtdStateChanged

    private void tbPedidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbPedidoMouseClicked
        int sel = tbPedido.getSelectedRow();
        TableModel modelo = tbPedido.getModel();

        int codigo = (int) modelo.getValueAt(sel, 3);
        pegarPedido(codigo);
        txtNomeCli.setText(modelo.getValueAt(sel, 4).toString());
        txtObrCliente.setText("");
    }//GEN-LAST:event_tbPedidoMouseClicked

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        try {
            if (txtCod.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Escolha um pedido!", "Aviso", JOptionPane.WARNING_MESSAGE);
            } else {
                int op = JOptionPane.showConfirmDialog(null, String.format("Deseja mesmo cancelar o pedido?", txtCod.getText().trim()), "Confirme", JOptionPane.YES_NO_OPTION);
                if (op == JOptionPane.YES_OPTION) {
                    ConPedidos conPedido = new ConPedidos();
                    Pedidos pedido = new Pedidos();

                    int codigo = Integer.parseInt(txtCod.getText());

                    pedido = conPedido.pegarPedido(codigo);

                    conPedido.cancelar(codigo);

                    JOptionPane.showMessageDialog(null, "Pedido de ID " + pedido.getCodigo() + " Cancelado.", "Aviso", JOptionPane.WARNING_MESSAGE);

                    limpar();
                    listar();

                    //validar();
                }

            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        try {
            Pedidos pedido = new Pedidos();
            ConPedidos conPedido = new ConPedidos();

            if (txtCod.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Selecione um pedido!", "Aviso", JOptionPane.WARNING_MESSAGE);
            } else if (cbStatus.getSelectedIndex() == -1) {
                JOptionPane.showMessageDialog(null, "Status não selecionado!", "Aviso", JOptionPane.WARNING_MESSAGE);
            } else {
                int op = JOptionPane.showConfirmDialog(null, "Deseja mesmo editar o status do pedido?", "Confirme", JOptionPane.YES_NO_OPTION);
                if (op == JOptionPane.YES_OPTION) {
                    pedido.setCodigo(Integer.parseInt(txtCod.getText()));

                    pedido.setStatus(cbStatus.getSelectedItem().toString());
                    conPedido.editar(pedido);

                    JOptionPane.showMessageDialog(null, "Status atualizado com sucesso!");

                    listar();
                    limpar();
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        int op = JOptionPane.showConfirmDialog(null, "Deseja mesmo limpar todos os campos?", "Confirme", JOptionPane.YES_NO_OPTION);
        if (op == JOptionPane.YES_OPTION) {
            limpar();
            //validar();
        }
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed

        if (txtCli.getText().trim().isEmpty() || cbStatus.getSelectedIndex() == -1 || Integer.parseInt(String.valueOf(spiQtd.getValue())) == 0) {
            JOptionPane.showMessageDialog(null, "Preencha os campos obrigatórios! ", "Aviso", JOptionPane.WARNING_MESSAGE);
        } else {

            if (!txtCod.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Esse pedido já existe. \nClique no botão de limpar para cadastrar um novo pedido.", "Aviso", JOptionPane.WARNING_MESSAGE);
            } else {
                int op = JOptionPane.showConfirmDialog(null, String.format("Deseja mesmo cadastrar o pedido?", txtCli.getText().trim()), "Confirme", JOptionPane.YES_NO_OPTION);
                if (op == JOptionPane.YES_OPTION) {

                    Pedidos pedido = new Pedidos();
                    ConPedidos conPedido = new ConPedidos();

                    Atendimentos atendimento = new Atendimentos();
                    ConAtendimentos conAtend = new ConAtendimentos();

                    ConServicos conServ = new ConServicos();
                    Servicos servico = new Servicos();

                    ConFuncionarios conFunc = new ConFuncionarios();
                    Funcionarios func = new Funcionarios();

                    Login login = new Login();

                    conFunc.pegarFuncionario(login.getUsuario());

                    pedido.setCliente(Integer.parseInt(txtCli.getText().trim()));
                    pedido.setFuncionario(func.getCodigo());
                    pedido.setHora(txtHora.getText().trim());
                    pedido.setData(txtData.getText().trim());
                    pedido.setStatus(cbStatus.getSelectedItem().toString());

                    if (txtData.getText().trim().isEmpty()) {
                        pedido.setData(" ");
                    } else {
                        pedido.setData(txtData.getText().trim());
                    }

                    if (txtHora.getText().trim().isEmpty()) {
                        pedido.setHora(" ");
                    } else {
                        pedido.setHora(txtHora.getText().trim());
                    }

                    conPedido.cadastrar(pedido);

                    atendimento.setPedido(conAtend.pegarUltimoPedido());
                    atendimento.setServico(cbTipos.getSelectedIndex() + 1);

                    atendimento.setObs(txtObs.getText());
                    atendimento.setQtd(Integer.parseInt(String.valueOf(spiQtd.getValue())));

                    servico = conServ.pesquisarTipoServ(cbTipos.getSelectedIndex() + 1);

                    float preco = servico.getValor() * Integer.parseInt(String.valueOf(spiQtd.getValue()));

                    atendimento.setPreco(preco);

                    conAtend.cadastrar(atendimento);

                    JOptionPane.showMessageDialog(null, "Pedido cadastrado com sucesso!");

                    limpar();
                    listar();

                }
            }
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void txtCodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodActionPerformed

    private void cbStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbStatusActionPerformed

    private void cbStatusItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbStatusItemStateChanged
        if (cbStatus.getSelectedIndex() != -1) {
            txtObrStatus.setText("");
        }
    }//GEN-LAST:event_cbStatusItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> cbStatus;
    private javax.swing.JComboBox<String> cbTipos;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner spiQtd;
    private javax.swing.JTable tbPedido;
    private javax.swing.JTextField txtCli;
    private javax.swing.JTextField txtCod;
    private javax.swing.JTextField txtData;
    private javax.swing.JTextField txtFunc;
    private javax.swing.JTextField txtHora;
    private javax.swing.JTextField txtNomeCli;
    private javax.swing.JLabel txtObrCliente;
    private javax.swing.JLabel txtObrStatus;
    private javax.swing.JLabel txtObrTipo;
    private javax.swing.JTextArea txtObs;
    private javax.swing.JTextField txtPreco;
    // End of variables declaration//GEN-END:variables
}
